[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on = ["t"]
run = "plugin smart-tab"
desc = "Create a smart tab on the hovered dir"

[[mgr.prepend_keymap]]
on = ["M", "m"]
run = "plugin gvfs -- select-then-mount"
desc = "Select device then mount"

[[mgr.prepend_keymap]]
on = ["M", "m"]
run = "plugin gvfs -- select-then-mount --jump"
desc = "Select device to mount and jump to its mount point"

[[mgr.prepend_keymap]]
on = ["M", "R"]
run = "plugin gvfs -- remount-current-cwd-device"
desc = "Remount device under cwd"

[[mgr.prepend_keymap]]
on = ["M", "u"]
run = "plugin gvfs -- select-then-unmount"
desc = "Select device then unmount"

[[mgr.prepend_keymap]]
on = ["M", "u"]
run = "plugin gvfs -- select-then-unmount --eject"
desc = "Select device then eject"

[[mgr.prepend_keymap]]
on = ["M", "U"]
run = "plugin gvfs -- select-then-unmount --eject --force"
desc = "Select device then force to eject/unmount"

[[mgr.prepend_keymap]]
on = ["M", "a"]
run = "plugin gvfs -- add-mount"
desc = "Add a GVFS mount URI"

[[mgr.prepend_keymap]]
on = ["M", "e"]
run = "plugin gvfs -- edit-mount"
desc = "Edit a GVFS mount URI"

[[mgr.prepend_keymap]]
on = ["M", "r"]
run = "plugin gvfs -- remove-mount"
desc = "Remove a GVFS mount URI"

[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "plugin gvfs -- jump-to-device"
desc = "Select device then jump to its mount point"

[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "plugin gvfs -- jump-to-device --automount"
desc = "Automount then select device to jump to its mount point"

[[mgr.prepend_keymap]]
on = ["`", "`"]
run = "plugin gvfs -- jump-back-prev-cwd"
desc = "Jump back to the position before jumped to device"

[[mgr.prepend_keymap]]
on = ["M", "t"]
run = "plugin gvfs -- automount-when-cd"
desc = "Enable automount when cd to device under cwd"

[[mgr.prepend_keymap]]
on = ["M", "T"]
run = "plugin gvfs -- automount-when-cd --disabled"
desc = "Disable automount when cd to device under cwd"


[[mgr.prepend_keymap]]
on = "y"
run = [
  "yank",
  'plugin clipboard -- --action=copy --notify-unknown-display-server',
]

[[mgr.prepend_keymap]]
on = "<C-p>"
run = ['plugin clipboard -- --action=paste']

[[mgr.prepend_keymap]]
on = ["n", "b"]
run = "plugin squish -- build"
desc = "Squash Build"

[[mgr.prepend_keymap]]
on = ["n", "x"]
run = "plugin squish -- extract"
desc = "Squash Extract"

[[mgr.prepend_keymap]]
on = ["n", "X"]
run = "plugin squish -- extract-pick"
desc = "Squash Extract (pick path)"

[[mgr.prepend_keymap]]
on = ["n", "m"]
run = "plugin squish -- mount"
desc = "Squash Mount"

[[mgr.prepend_keymap]]
on = ["n", "u"]
run = "plugin squish -- unmount"
desc = "Squash Unmount"

[[mgr.prepend_keymap]]
on = ["Q"]
run = "quit"

[[mgr.prepend_keymap]]
on = ["q", "q"]
run = "plugin session-mgr -- save-and-quit"
desc = "Save session and quit"

[[mgr.prepend_keymap]]
on = ["q", "s"]
run = "plugin session-mgr -- save"
desc = "Save session"

[[mgr.prepend_keymap]]
on = ["q", "c"]
run = "plugin session-mgr -- chooser"
desc = "Session chooser"
