[mgr]
show_hidden = true

[opener]
smart_edit = [{ run = 'edit.sh %s', desc = "Smart edit (tmux/zellij)" }]

edit_tmux = [
  { run = 'tmux new-window -t main -- $EDITOR %s', desc = "Edit via tmux" },
]

edit_zellij = [
  { run = 'zellij action new-tab --close-on-exit -- $EDITOR %s', desc = "Edit via zellij" },
]

edit_editor = [{ run = '$EDITOR "%s"', desc = "Edit via Helix" }]

[open]
rules = [
  { mime = "text/*", use = [
    "smart_edit",
    "edit_tmux",
    "edit_zellij",
    "edit_helix",
    "edit_editor",
  ] },
  { mime = "application/javascript", use = [
    "smart_edit",
    "edit_tmux",
    "edit_zellij",
    "edit_helix",
    "edit_editor",
  ] },
  { mime = "application/json", use = [
    "smart_edit",
    "edit_tmux",
    "edit_zellij",
    "edit_helix",
    "edit_editor",
  ] },
]
