---
# Host-specific Configuration
system_hostname: methyl-bazzite

# Flatpak Configuration (Bazzite-specific)
system_flatpaks:
  - com.github.tchx84.Flatseal
  - it.mijorus.gearlever
  - runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/24.08
  - com.github.Matoking.protontricks
  - org.gtk.Gtk3theme.Adwaita-dark
  - org.kde.filelight
  - org.kde.gwenview
  - org.kde.haruna
  - org.kde.kcalc
  - org.kde.okular
  - org.gnome.Papers
user_flatpaks:
  - com.github.zocker_160.SyncThingy
  - com.vysp3r.ProtonPlus
  - com.usebottles.bottles
  - dev.vencord.Vesktop
skip_flatpaks:
  - io.github.peazip.PeaZip
  - com.brave.Browser
  - org.mozilla.firefox

# Feature Toggles
enable_appimages: true
enable_ghostty: false
enable_alacritty: false
enable_nix: true
enable_brew: true
enable_btrfs_snapper: false
enable_vfio: false
enable_distrobox: false

install_brave: "distrobox"

# Brew Packages (Bazzite-specific)
brew_packages:
  - ansible
  - bat
  - eza
  - fd
  - fish
  - fzf
  - khal
  - vdirsyncer
  - lazygit
  - neovim
  - rdfind
  - ripgrep
  - rustup
  - starship
  - trash-cli
  - yazi
  - zellij
  - zoxide
