---
# Host-specific Configuration
system_hostname: methyl-cachyos

# Package Management (Arch-specific)
base_packages:
  - ansible
  - base-devel
  - bat
  - curl
  - distrobox
  - earlyoom
  - eza
  - fd
  - file
  - fish
  - fuse2
  - fzf
  - git
  - gnupg
  - helix
  - kitty
  - lazygit
  - lib32-mangohud
  - lib32-pulseaudio
  - libcurl-gnutls
  - libssh2
  - lib32-mangohud
  - mangohud
  - neovim
  - openrgb
  - podman
  - procps-ng
  - protontricks
  - rdfind
  - ripgrep
  - rsync
  - rustup
  - sshfs
  - starship
  - steam
  - trash-cli
  - tmux
  - tuned
  - unzip
  - winetricks
  - wl-clipboard
  - yay
  - yazi
  - zellij
  - zoxide
  - zstd

aur_builder_user: yaybuildr
aur_helper_pkg: yay-bin
aur_helper: yay
aur_packages:
  - downgrade
  - brlaser-git

# Flatpak Configuration (Cachyos-specific)
system_flatpaks:
  - com.github.tchx84.Flatseal
  - it.mijorus.gearlever
  - runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/24.08
  - com.github.Matoking.protontricks
  - org.gnome.Papers
user_flatpaks:
  - com.vysp3r.ProtonPlus
  - com.usebottles.bottles
  - dev.vencord.Vesktop
skip_flatpaks:
  - io.github.peazip.PeaZip
  - com.brave.Browser

# Feature Toggles
enable_appimages: false
enable_nix: false
enable_brew: false
enable_btrfs_snapper: true
enable_vfio: false
enable_distrobox: false
