---
all:
  children:
    local:
      hosts:
        methyl-cachyos:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
        methyl-bazzite:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
