---
- name: Process tmux configuration
  tags: [extra, dotfiles, dotfiles_tmux]
  block:
    - name: Check if tmux binary exists
      ansible.builtin.command: which tmux
      register: tmux_check
      ignore_errors: true
      changed_when: false
      check_mode: false

    - name: Process tmux with tuckr
      when: tmux_check.rc == 0
      block:
        - name: Manage tmux config with tuckr
          tuckr_manage:
            name: "tmux"
            state: present

        - name: Create symlink for tmux.conf
          ansible.builtin.file:
            src: "{{ home_dir }}/.config/tmux/tmux.conf"
            dest: "{{ home_dir }}/.tmux.conf"
            state: link
            force: true

        - name: Special handling for tmux plugins
          block:
            - name: Ensure tmux plugins directory exists
              ansible.builtin.file:
                path: "{{ home_dir }}/.config/tmux/plugins"
                state: directory
                mode: "0755"

            - name: Check if TPM directory is empty
              ansible.builtin.stat:
                path: "{{ home_dir }}/.config/tmux/plugins/tpm"
              register: tpm_dir

            - name: Check if TPM git repository exists
              ansible.builtin.stat:
                path: "{{ home_dir }}/.config/tmux/plugins/tpm/.git"
              register: tpm_git_dir

            - name: Clone TPM if not already cloned
              ansible.builtin.git:
                repo: "https://github.com/tmux-plugins/tpm"
                dest: "{{ home_dir }}/.config/tmux/plugins/tpm"
                version: 99469c4a9b1ccf77fade25842dc7bafbc8ce9946 # pinned to 02-27-23
              when: not tpm_git_dir.stat.exists

            - name: Set executable permissions for TPM
              ansible.builtin.file:
                path: "{{ tpm_item }}"
                mode: "0755"
              loop:
                - "{{ home_dir }}/.config/tmux/plugins/tpm/tpm"
                - "{{ home_dir }}/.config/tmux/plugins/tpm/bindings"
              loop_control:
                loop_var: tpm_item
                label: "Fixing permissions for {{ tpm_item | basename }}"

            - name: Set executable permissions for TPM bindings
              ansible.builtin.file:
                path: "{{ binding_item }}"
                mode: "0755"
              loop: "{{ query('fileglob', home_dir + '/.config/tmux/plugins/tpm/bindings/*') }}"
              loop_control:
                loop_var: binding_item
                label: "Fixing permissions for {{ binding_item | basename }}"
