- name: Process tmux configuration
  tags: [extra, dotfiles, dotfiles_tmux]
  block:
    - name: Check if tmux is installed
      ansible.builtin.command: command -v tmux
      register: tmux_check
      ignore_errors: true
      changed_when: false

    - name: Configure tmux if installed
      when: tmux_check.rc is defined and tmux_check.rc == 0
      block:
        - name: Manage tmux config with tuckr
          tuckr_manage:
            name: "tmux"
            state: present

        - name: Create tmux.conf symlink
          ansible.builtin.file:
            src: "{{ home_dir }}/.config/tmux/tmux.conf"
            dest: "{{ home_dir }}/.tmux.conf"
            state: link
            force: true

        - name: Ensure plugins directory structure exists
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: "0755"
          loop:
            - "{{ home_dir }}/.config/tmux/plugins"
            - "{{ home_dir }}/.config/tmux/plugins/tpm"

        - name: Check TPM repository status
          ansible.builtin.stat:
            path: "{{ home_dir }}/.config/tmux/plugins/tpm/.git"
          register: tpm_repo

        - name: Clone TPM if needed
          ansible.builtin.git:
            repo: "https://github.com/tmux-plugins/tpm"
            dest: "{{ home_dir }}/.config/tmux/plugins/tpm"
            version: 99469c4a9b1ccf77fade25842dc7bafbc8ce9946 # pin to 02-27-23
          when: not tpm_repo.stat.exists

        - name: Set permissions for TPM executables
          ansible.builtin.file:
            path: "{{ item.path }}"
            mode: "0755"
          loop:
            - { path: "{{ home_dir }}/.config/tmux/plugins/tpm/tpm" }
            - { path: "{{ home_dir }}/.config/tmux/plugins/tpm/bindings" }
            - { path: "{{ home_dir }}/.config/tmux/plugins/tpm/scripts/install_plugins.sh" }
            - { path: "{{ home_dir }}/.config/tmux/plugins/tpm/scripts/update_plugin.sh" }
            - { path: "{{ home_dir }}/.config/tmux/plugins/tpm/scripts/clean_plugins.sh" }
          when: tpm_repo.stat.exists
