--password-store=kwallet6
--enable-features=UseOzonePlatform
--ozone-platform=wayland
--force-color-profile=hdr10
--enable-experimental-web-platform-features
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecoder,AcceleratedVideoEncoder
