[prime]
--prefer-vk-device 1
export VK_DEVICE_FILTER=discrete

[fallback]
-f -w 1920 -h 1080 -W 1920 -H 1080

[std]
-f -w 2560 -h 1440 -W 2560 -H 1440

[nstd]
-f -w 2560 -h 1440 -W 2560 -H 1440 --backend=sdl
export SDL_VIDEODRIVER=x11

[hdr]
--hdr-enabled --hdr-itm-enabled
export DXVK_HDR=1
export PROTON_ENABLE_HDR=1

[fsr]
-F fsr --sharpness 0

[vsrSDD]
-f -w 1280 -h 720 -W 2560 -H 1440

[vsr4k]
-f -w 2560 -h 1440 -W 3840 -H 2160
