[[backup]]
path = "$HOME/.config"
output = "BraveSoftware_backup"
include = ["BraveSoftware"]
exclude = ["Cache", "Code Cache", "GPUCache"]

[[backup]]
path = "$HOME/.var/app/com.brave.Browser/config"
output = "BraveSoftware-var_backup"
include = ["BraveSoftware"]
exclude = ["Cache", "Code Cache", "GPUCache"]

[[backup]]
path = "$HOME/.config"
output = "heroic_backup"
include = ["heroic"]
exclude = ["Cache", "Code Cache", "GPUCache"]

[[backup]]
path = "$HOME/.config"
output = "Code_backup"
include = ["Code"]
exclude = ["Cache", "Code Cache", "GPUCache"]

[[backup]]
path = "$HOME/.config"
output = "vesktop_backup"
include = ["vesktop"]
exclude = ["Cache", "Code Cache", "GPUCache"]

[[backup]]
path = "$HOME"
output = "mozilla_backup"
include = [".mozilla"]
exclude = ["OfflineCache", "safebrowsing", "startupCache", "cache2"]

[[backup]]
path = "$HOME/.steam/steam/userdata/22932417/config"
output = "steam_userdata_backup"
include = ["grid", "librarycache", "shortcuts.vdf"]

[[backup]]
path = "/etc/ananicy.d"
output = "ananicy-user-rules_backup"
include = ["01-user"]
