---
- name: "Process swap file using systemd_mount module"
  systemd_mount:
    src_dir: "{{ role_path }}/files"
    swap_file: "{{ swap_item.path | basename }}"
    dst: "/etc/systemd/system"
    os_type: "{{ os_release_id }}"
    mode: "single_swap"
    state: "present"
  become: true
  register: swap_result

- name: "Debug swap result"
  ansible.builtin.debug:
    var: swap_result
    verbosity: 1
