---
- name: "Remove existing mounts"
  systemd_mount:
    state: absent
    os_type: "{{ os_release_id }}"
  become: true
  register: mounts_removed

- name: "Debug removed mounts"
  ansible.builtin.debug:
    var: mounts_removed
    verbosity: 1
