general.import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.99
dimensions.columns = 110
dimensions.lines = 38
decorations = "Full"
decorations_theme_variant = "Dark"
option_as_alt = "OnlyLeft"

[font]
normal.family = "Iosevka Nerd Font"
bold.family = "Iosevka Nerd Font"
italic.family = "Iosevka Nerd Font"
bold_italic.family = "Iosevka Nerd Font"
#
# normal.family = "JetBrainsMono Nerd Font"
# bold.family = "JetBrainsMono Nerd Font"
# italic.family = "JetBrainsMono Nerd Font"
# bold_italic.family = "JetBrainsMono Nerd Font"
size = 13

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500

[mouse]
hide_when_typing = true
