---
galaxy_info:
  author: "methyl"
  license: "MIT"
  description: "System mounts configuration"
  min_ansible_version: "2.14"
  platforms:
    - name: Fedora
      versions: [all]

dependencies: []
