[preferred]
default=gnome;gtk;kde
org.freedesktop.impl.portal.OpenURI=kde
org.freedesktop.impl.portal.Secret=kde
org.freedesktop.impl.portal.FileChooser=kde
org.freedesktop.impl.portal.Print=kde
org.freedesktop.impl.portal.ScreenCast=gnome
org.freedesktop.impl.portal.Screenshot=gnome
