[Service]
ExecStart=
ExecStart=/usr/bin/beesd --no-timestamps %i
Restart=on-failure
RestartSec=10s
SuccessExitStatus=124
# Automatically stop beesd if it runs longer than 4 hours (14400 seconds)
RuntimeMaxSec=14400
CPUSchedulingPolicy=idle
OOMScoreAdjust=500
Nice=19
IOSchedulingClass=idle
IOSchedulingPriority=7
