#!/usr/bin/env ansible-playbook
---
# Run with: ansible-playbook plays/roles/btrfs-setup.yml
# Or with check mode: ansible-playbook plays/roles/btrfs-setup.yml --check
- name: BTRFS setup
  hosts: methyl-cachyos methyl-bazzite
  gather_facts: true

  pre_tasks:
    - name: Run system facts gathering
      ansible.builtin.include_role:
        name: system_facts
      tags: [always]

  roles:
    - btrfs
