wireplumber.components = [
  {
    name = "browser-gate-route.lua",
    type = "script/lua",
    provides = "custom.browser-gate-route"
  }
  {
    name = "hdmi-gate-route.lua",
    type = "script/lua",
    provides = "custom.hdmi-gate-route"
  }
]
wireplumber.profiles = {
  main = {
    custom.browser-gate-route = required
    custom.hdmi-gate-route = required
  }
}
