wireplumber.components = [
  {
    name = "browser-custom-route.lua",
    type = "script/lua",
    provides = "custom.browser-custom-route"
  }
]
wireplumber.profiles = {
  main = {
    custom.browser-custom-route = required
  }
}
