wireplumber.components = [
  {
    name = "custom-gate-route.lua",
    type = "script/lua",
    provides = "custom.custom-gate-route"
  }
  {
    name = "browser-gate-route.lua",
    type = "script/lua",
    provides = "custom.browser-gate-route"
  }
]
wireplumber.profiles = {
  main = {
    custom.custom-gate-route = required
    custom.browser-gate-route = required
  }
}
