wireplumber.components = [
  {
    name = "gate-route.lua",
    type = "script/lua",
    provides = "hooks.custom.gate-route"
  }
]
wireplumber.profiles = {
  main = {
    hooks.custom.gate-route = optional
  }
}
